on: [push]

jobs:
  analyzerJob:
    runs-on: ubuntu-latest
    name: A job to check identifier names
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Analyzer
        uses: Remoliveira/id-analyzer-action4@v3
