on: [push]

jobs:
  analyzerJob:
    runs-on: ubuntu-latest
    name: A job to say thank you
    steps:
      - name: Analyzer
        id: hello
        uses: Remoliveira/id-analyzer-action3@000v
        with:
          repo: ActionTest
          owner: Remoliveira
          branch: master
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.out }}"
