on: [push]

jobs:
  analyzerJob:
    runs-on: ubuntu-latest
    name: A job to say thank you
    needs: firstWorkflow
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Analyzer
        id: hello
        uses: Remoliveira/id-analyzer-action4@v2
