on: [push]

jobs:
  analyzerJob:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: Remoliveira/id-analyzer-action3@v1
        with:
          repo: ActionTest
          owner: Remoliveira
          branch: master
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.out }}"
